version: 2
outputDir: build
apisToHide: []
apiMap:
- name: Metadata APIs
  resources:
  - kind: Binding
    version: v1
  - kind: ComponentStatus
    version: v1
  - kind: ConfigMap
    version: v1
  - kind: ControllerRevision
    group: apps
    version: v1
  - kind: Event
    group: events.k8s.io
    version: v1
  - kind: Event
    version: v1
  - kind: Lease
    group: coordination.k8s.io
    version: v1
  - kind: Namespace
    version: v1
- name: Project APIs
  resources:
  - kind: Project
    group: project.openshift.io
    version: v1
  - kind: ProjectRequest
    group: project.openshift.io
    version: v1
- name: Workloads APIs
  resources:
  - kind: BuildConfig
    group: build.openshift.io
    version: v1
  - kind: Build
    group: build.openshift.io
    version: v1
  - kind: CronJob
    group: batch
    version: v1beta1
  - kind: DaemonSet
    group: apps
    version: v1
  - kind: Deployment
    group: apps
    version: v1
  - kind: DeploymentConfig
    group: apps.openshift.io
    version: v1
  - kind: Job
    group: batch
    version: v1
  - kind: Pod
    version: v1
  - kind: ReplicationController
    version: v1
  - kind: PersistentVolume
    version: v1
  - kind: ReplicaSet
    group: apps
    version: v1
  - kind: StatefulSet
    group: apps
    version: v1
