# From github.com/kubernetes-incubator/reference-docs/gen-apidocs/generators/config.yaml
# A combation of TOC, API groups, and regex for matching HTTP operations
example_location: "examples"
api_groups:
  - "AdmissionRegistration"
  - "ApiExtensions"
  - "ApiRegistration"
  - "Apps"
  - "AuditRegistration"
  - "Authentication"
  - "Authorization"
  - "Autoscaling"
  - "Batch"
  - "Certificates"
  - "Coordination"
  - "Core"
  - "Discovery"
  - "Extensions"
  - "Meta"
  - "Networking"
  - "Node"
  - "Policy"
  - "Rbac"
  - "Scheduling"
  - "Settings"
  - "Storage"
