# Match rules for {Group,Version,Kind}
# Order does matter; Less specific rules may match
# incorrectly, so must be specified after rules with
# greater specificity.
# (Group = io.openshift vs Group = io.openshift.operator)

- rule: "com.coreos"
  match: com\.coreos\.(?<group>[^\.]+)\.(?<version>[^\.]+)\.(?<kind>[^\.]+)
  groupOverride: <group>.coreos.com

# io.cncf.cni.k8s.v1.NetworkAttachmentDefinitionList
# io.cncf.cni.whereabouts.v1alpha1.IPPoolList
- rule: "io.cncf.cni"
  match: io\.cncf\.cni\.(?<group>[^\.]+)\.(?<version>[^\.]+)\.(?<kind>[^\.]+)
  groupOverride: <group>.cni.cncf.io

- rule: "io.metal3"
  match: io\.metal3\.(?<version>[^\.]+)\.(?<kind>[^\.]+)
  groupOverride: metal3.io

# com.github.operator-framework.operator-lifecycle-manager.pkg.package-server.apis.apps.v1alpha1.AppLink
- rule: "com.github.operator-framework"
  match: com\.github\.operator-framework\..+(?:(operators|apps))\.(?<version>[^\.]+)\.(?<kind>[^\.]+)
  groupOverride: packages.operators.coreos.com

# com.github.operator-framework.operator-lifecycle-manager.pkg.lib.version.OperatorVersion
- rule: "com.github.operator-framework.operator-lifecycle-manager.pkg.lib.version.OperatorVersion"
  match: com\.github\.operator-framework\..+\.(?<version>[^\.]+)\.(?<kind>[^\.]+)
  groupOverride: packages.operators.coreos.com

# io.k8s.storage.snapshot.v1beta1.VolumeSnapshot
- rule: io.k8s.storage.snapshot
  match: io\.k8s\.storage\.(?<group>[^\.]+)\.(?<version>[^\.]+)\.(?<kind>[^\.]+)
  groupOverride: <group>.storage.k8s.io

# io.k8s.apimachinery.pkg.apis.meta.v1.WatchEvent
- rule: "io.k8s.apimachinery"
  match: io\.k8s\..+(?:apis\.)?\.(?<group>[^\.]+)\.(?<version>[^\.]+)\.(?<kind>[^\.]+)

# io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionVersion
- rule: "io.k8s.apiextensions-apiserver"
  match: io\.k8s\..+(?:apis\.)?\.(?<group>[^\.]+)\.(?<version>[^\.]+)\.(?<kind>[^\.]+)
  groupOverride: <group>.k8s.io

# io.k8s.kube-aggregator.pkg.apis.apiregistration.v1.APIService
- rule: "io.k8s.kube-aggregator"
  match: io\.k8s\..+(?:apis\.)?\.(?<group>[^\.]+)\.(?<version>[^\.]+)\.(?<kind>[^\.]+)
  groupOverride: <group>.k8s.io

- rule: "io.k8s.api.rbac"
  match: io\.k8s\.api\.?(?<group>[^\.]+)\.(?<version>[^\.]+)\.(?<kind>[^\.]+)
  groupOverride: <group>.authorization.k8s.io

# These are legacy groups
- rule: "io.k8s.api"
  match: io\.k8s\.api\.?(?<group>(apps|autoscaling|batch|core|extensions|policy|rbac)+)\.(?<version>[^\.]+)\.(?<kind>[^\.]+)

- rule: "io.k8s.api"
  match: io\.k8s\.api\.?(?<group>[^\.]+)\.(?<version>[^\.]+)\.(?<kind>[^\.]+)
  groupOverride: <group>.k8s.io

# io.k8s.migration.v1alpha1.StorageStateList
- rule: "io.k8s"
  match: io\.k8s\.(?:api\.)?(?<group>[^\.]+)\.(?<version>[^\.]+)\.(?<kind>[^\.]+)
  groupOverride: <group>.k8s.io

# io.openshift.operator.imageregistry.v1.Config
- rule: io.openshift.operator
  match: io\.openshift\.operator\.(?<group>[^\.]+)\.(?<version>[^\.]+)\.(?<kind>[^\.]+)
  groupOverride: <group>.operator.openshift.io

# io.openshift.operator.v1.Network
- rule: "io.openshift"
  match: io\.openshift\.(?<group>[^\.]+)\.(?<version>[^\.]+)\.(?<kind>[^\.]+)
  groupOverride: <group>.openshift.io

# com.github.openshift.api.apps.v1.DeploymentConfig
- rule: "com.github.openshift.api"
  match: com\.github\.openshift\.api\.(?<group>[^\.]+)\.(?<version>[^\.]+)\.(?<kind>[^\.]+)
  groupOverride: <group>.openshift.io
