- name: OpenShift APIs
  resources:
  - name: Binding
    version: v1
    group: core
  - name: ComponentStatus
    version: v1
    group: core
  - name: ConfigMap
    version: v1
    group: core
  - name: Endpoints
    version: v1
    group: core
  - name: Event
    version: v1
    group: core
  - name: LimitRange
    version: v1
    group: core
  - name: Namespace
    version: v1
    group: core
  - name: Node
    version: v1
    group: core
  - name: PersistentVolume
    version: v1
    group: core
  - name: PersistentVolumeClaim
    version: v1
    group: core
  - name: Pod
    version: v1
    group: core
  - name: PodTemplate
    version: v1
    group: core
  - name: ReplicationController
    version: v1
    group: core
  - name: ResourceQuota
    version: v1
    group: core
  - name: Secret
    version: v1
    group: core
  - name: Service
    version: v1
    group: core
  - name: ServiceAccount
    version: v1
    group: core
  - name: MutatingWebhookConfiguration
    version: v1
    group: admissionregistration
  - name: ValidatingWebhookConfiguration
    version: v1
    group: admissionregistration
  - name: CustomResourceDefinition
    version: v1
    group: apiextensions
  - name: APIService
    version: v1
    group: apiregistration
  - name: ControllerRevision
    version: v1
    group: apps
  - name: DaemonSet
    version: v1
    group: apps
  - name: Deployment
    version: v1
    group: apps
  - name: ReplicaSet
    version: v1
    group: apps
  - name: StatefulSet
    version: v1
    group: apps
  - name: DeploymentConfig
    version: v1
    group: apps.openshift.io
  - name: TokenReview
    version: v1
    group: authentication
  - name: LocalSubjectAccessReview
    version: v1
    group: authorization
  - name: SelfSubjectAccessReview
    version: v1
    group: authorization
  - name: SelfSubjectRulesReview
    version: v1
    group: authorization
  - name: SubjectAccessReview
    version: v1
    group: authorization
  - name: ClusterRole
    version: v1
    group: authorization.openshift.io
  - name: ClusterRoleBinding
    version: v1
    group: authorization.openshift.io
  - name: LocalResourceAccessReview
    version: v1
    group: authorization.openshift.io
  - name: LocalSubjectAccessReview
    version: v1
    group: authorization.openshift.io
  - name: ResourceAccessReview
    version: v1
    group: authorization.openshift.io
  - name: Role
    version: v1
    group: authorization.openshift.io
  - name: RoleBinding
    version: v1
    group: authorization.openshift.io
  - name: RoleBindingRestriction
    version: v1
    group: authorization.openshift.io
  - name: SelfSubjectRulesReview
    version: v1
    group: authorization.openshift.io
  - name: SubjectAccessReview
    version: v1
    group: authorization.openshift.io
  - name: SubjectRulesReview
    version: v1
    group: authorization.openshift.io
  - name: HorizontalPodAutoscaler
    version: v1
    group: autoscaling
  - name: ClusterAutoscaler
    version: v1
    group: autoscaling.openshift.io
  - name: MachineAutoscaler
    version: v1beta1
    group: autoscaling.openshift.io
  - name: CronJob
    version: v1beta1
    group: batch
  - name: Job
    version: v1
    group: batch
  - name: Build
    version: v1
    group: build.openshift.io
  - name: BuildConfig
    version: v1
    group: build.openshift.io
  - name: CertificateSigningRequest
    version: v1beta1
    group: certificates
  - name: CredentialsRequest
    version: v1
    group: cloudcredential.openshift.io
  - name: APIServer
    version: v1
    group: config.openshift.io
  - name: Authentication
    version: v1
    group: config.openshift.io
  - name: Build
    version: v1
    group: config.openshift.io
  - name: ClusterOperator
    version: v1
    group: config.openshift.io
  - name: ClusterVersion
    version: v1
    group: config.openshift.io
  - name: Console
    version: v1
    group: config.openshift.io
  - name: DNS
    version: v1
    group: config.openshift.io
  - name: FeatureGate
    version: v1
    group: config.openshift.io
  - name: Image
    version: v1
    group: config.openshift.io
  - name: Infrastructure
    version: v1
    group: config.openshift.io
  - name: Ingress
    version: v1
    group: config.openshift.io
  - name: Network
    version: v1
    group: config.openshift.io
  - name: OAuth
    version: v1
    group: config.openshift.io
  - name: OperatorHub
    version: v1
    group: config.openshift.io
  - name: Project
    version: v1
    group: config.openshift.io
  - name: Proxy
    version: v1
    group: config.openshift.io
  - name: Scheduler
    version: v1
    group: config.openshift.io
  - name: ConsoleCLIDownload
    version: v1
    group: console.openshift.io
  - name: ConsoleExternalLogLink
    version: v1
    group: console.openshift.io
  - name: ConsoleLink
    version: v1
    group: console.openshift.io
  - name: ConsoleNotification
    version: v1
    group: console.openshift.io
  - name: ConsoleYAMLSample
    version: v1
    group: console.openshift.io
  - name: Lease
    version: v1
    group: coordination
  - name: Event
    version: v1beta1
    group: events
  - name: DaemonSet
    version: v1beta1
    group: extensions
  - name: Deployment
    version: v1beta1
    group: extensions
  - name: Ingress
    version: v1beta1
    group: extensions
  - name: NetworkPolicy
    version: v1beta1
    group: extensions
  - name: PodSecurityPolicy
    version: v1beta1
    group: extensions
  - name: ReplicaSet
    version: v1beta1
    group: extensions
  - name: Image
    version: v1
    group: image.openshift.io
  - name: ImageSignature
    version: v1
    group: image.openshift.io
  - name: ImageStream
    version: v1
    group: image.openshift.io
  - name: ImageStreamImage
    version: v1
    group: image.openshift.io
  - name: ImageStreamImport
    version: v1
    group: image.openshift.io
  - name: ImageStreamMapping
    version: v1
    group: image.openshift.io
  - name: ImageStreamTag
    version: v1
    group: image.openshift.io
  - name: Config
    version: v1
    group: imageregistry.operator.openshift.io
  - name: DNSRecord
    version: v1
    group: ingress.operator.openshift.io
  - name: NetworkAttachmentDefinition
    version: v1
    group: k8s.cni.cncf.io
  - name: Machine
    version: v1beta1
    group: machine.openshift.io
  - name: MachineHealthCheck
    version: v1beta1
    group: machine.openshift.io
  - name: MachineSet
    version: v1beta1
    group: machine.openshift.io
  - name: ContainerRuntimeConfig
    version: v1
    group: machineconfiguration.openshift.io
  - name: ControllerConfig
    version: v1
    group: machineconfiguration.openshift.io
  - name: KubeletConfig
    version: v1
    group: machineconfiguration.openshift.io
  - name: MachineConfig
    version: v1
    group: machineconfiguration.openshift.io
  - name: MachineConfigPool
    version: v1
    group: machineconfiguration.openshift.io
  - name: MCOConfig
    version: v1
    group: machineconfiguration.openshift.io
  - name: BareMetalHost
    version: v1alpha1
    group: metal3.io
  - name: StorageState
    version: v1alpha1
    group: migration
  - name: StorageVersionMigration
    version: v1alpha1
    group: migration
  - name: Alertmanager
    version: v1
    group: monitoring.coreos.com
  - name: PodMonitor
    version: v1
    group: monitoring.coreos.com
  - name: Prometheus
    version: v1
    group: monitoring.coreos.com
  - name: PrometheusRule
    version: v1
    group: monitoring.coreos.com
  - name: ServiceMonitor
    version: v1
    group: monitoring.coreos.com
  - name: ClusterNetwork
    version: v1
    group: network.openshift.io
  - name: EgressNetworkPolicy
    version: v1
    group: network.openshift.io
  - name: HostSubnet
    version: v1
    group: network.openshift.io
  - name: NetNamespace
    version: v1
    group: network.openshift.io
  - name: OperatorPKI
    version: v1
    group: network.operator.openshift.io
  - name: Ingress
    version: v1beta1
    group: networking
  - name: NetworkPolicy
    version: v1
    group: networking
  - name: RuntimeClass
    version: v1beta1
    group: node
  - name: OAuthAccessToken
    version: v1
    group: oauth.openshift.io
  - name: OAuthAuthorizeToken
    version: v1
    group: oauth.openshift.io
  - name: OAuthClient
    version: v1
    group: oauth.openshift.io
  - name: OAuthClientAuthorization
    version: v1
    group: oauth.openshift.io
  - name: Authentication
    version: v1
    group: operator.openshift.io
  - name: Console
    version: v1
    group: operator.openshift.io
  - name: DNS
    version: v1
    group: operator.openshift.io
  - name: ImageContentSourcePolicy
    version: v1alpha1
    group: operator.openshift.io
  - name: IngressController
    version: v1
    group: operator.openshift.io
  - name: KubeAPIServer
    version: v1
    group: operator.openshift.io
  - name: KubeControllerManager
    version: v1
    group: operator.openshift.io
  - name: KubeScheduler
    version: v1
    group: operator.openshift.io
  - name: KubeStorageVersionMigrator
    version: v1
    group: operator.openshift.io
  - name: Network
    version: v1
    group: operator.openshift.io
  - name: OpenShiftAPIServer
    version: v1
    group: operator.openshift.io
  - name: OpenShiftControllerManager
    version: v1
    group: operator.openshift.io
  - name: ServiceCA
    version: v1
    group: operator.openshift.io
  - name: ServiceCatalogAPIServer
    version: v1
    group: operator.openshift.io
  - name: ServiceCatalogControllerManager
    version: v1
    group: operator.openshift.io
  - name: CatalogSource
    version: v1alpha1
    group: operators.coreos.com
  - name: CatalogSourceConfig
    version: v1
    group: operators.coreos.com
  - name: ClusterServiceVersion
    version: v1alpha1
    group: operators.coreos.com
  - name: InstallPlan
    version: v1alpha1
    group: operators.coreos.com
  - name: OperatorGroup
    version: v1
    group: operators.coreos.com
  - name: OperatorSource
    version: v1
    group: operators.coreos.com
  - name: Subscription
    version: v1alpha1
    group: operators.coreos.com
  - name: PackageManifest
    version: v1
    group: packages.operators.coreos.com
  - name: PodDisruptionBudget
    version: v1beta1
    group: policy
  - name: PodSecurityPolicy
    version: v1beta1
    group: policy
  - name: Project
    version: v1
    group: project.openshift.io
  - name: ProjectRequest
    version: v1
    group: project.openshift.io
  - name: AppliedClusterResourceQuota
    version: v1
    group: quota.openshift.io
  - name: ClusterResourceQuota
    version: v1
    group: quota.openshift.io
  - name: ClusterRole
    version: v1
    group: rbac
  - name: ClusterRoleBinding
    version: v1
    group: rbac
  - name: Role
    version: v1
    group: rbac
  - name: RoleBinding
    version: v1
    group: rbac
  - name: Route
    version: v1
    group: route.openshift.io
  - name: Config
    version: v1
    group: samples.operator.openshift.io
  - name: PriorityClass
    version: v1
    group: scheduling
  - name: PodSecurityPolicyReview
    version: v1
    group: security.openshift.io
  - name: PodSecurityPolicySelfSubjectReview
    version: v1
    group: security.openshift.io
  - name: PodSecurityPolicySubjectReview
    version: v1
    group: security.openshift.io
  - name: RangeAllocation
    version: v1
    group: security.openshift.io
  - name: SecurityContextConstraints
    version: v1
    group: security.openshift.io
  - name: CSIDriver
    version: v1beta1
    group: storage
  - name: CSINode
    version: v1beta1
    group: storage
  - name: StorageClass
    version: v1
    group: storage
  - name: VolumeAttachment
    version: v1
    group: storage
  - name: VolumeSnapshot
    version: v1beta1
    group: snapshot.storage.k8s.io
  - name: BrokerTemplateInstance
    version: v1
    group: template.openshift.io
  - name: Template
    version: v1
    group: template.openshift.io
  - name: Template
    version: v1
    group: template.openshift.io
  - name: TemplateInstance
    version: v1
    group: template.openshift.io
  - name: Tuned
    version: v1
    group: tuned.openshift.io
  - name: Group
    version: v1
    group: user.openshift.io
  - name: Identity
    version: v1
    group: user.openshift.io
  - name: User
    version: v1
    group: user.openshift.io
  - name: UserIdentityMapping
    version: v1
    group: user.openshift.io
